### ISSUE TITLE
TabbedPage don't show on Gorilla Player

### ISSUE THREAD

**Issue by JarJarBinkz** [UXDivers/Gorilla-Player-Support-And-Issues#38] opened 2016-02-12 12:11 UTC
Gorilla Player with Visual Studio 2015 Update 1 and Xamarin Studio don't show a TabbedPage on the mobilephone.

```
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Core.TestTabbedPage" x:Name="TestPage">

    <ContentPage Title="Test1">
      <Label>Hello</Label>
    </ContentPage>

    <ContentPage Title="Test2">
      <Label>Yuhu</Label>
    </ContentPage>

</TabbedPage>
```

In Xamarin Studio the menu "Stick Gorilla to this" is disabled.
![tabbedpages](https://cloud.githubusercontent.com/assets/16030219/13006553/fe040006-d189-11e5-8b23-4be2f1878f40.png)

**Comment by jpbrocca** [comment] 2016-02-12 12:22
Hi @JarJarBinkz thanks.

I will close this bug since it is a duplicate of #22.

Regards,
JP

**Closed by jpbrocca** 2016-02-12 12:22 UTC
Labels: duplicate
